pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

trigger:
- master
- dev
- features/*

- task: DotNetCoreInstaller@0
  displayName: Installing .net core sdk 2.2.100
  inputs:
    version: '2.2.100'
    packageType: sdk

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
